### ISSUE TITLE
[FEATURE] Nick Command

### ISSUE THREAD

**Issue by Glukose1** [nplay-team/moderation-bot#17]
- [ ] /moderation setnick [member + nickname]

**Comment by SimuPlays** [comment]
Ehrlich gesagt sehe ich keinen konkreten Nutzen in diesem Command. Den User kurz suchen, Rechtsklick und Nickname ändern ist für meine Begriffe leichter. 
Höchstens um eine Änderung aktiv zu loggen, falls das über die Default-Vorgehensweise nicht geht - aber auch hier dürften Nicknameänderungen deutlich unwichtiger sein als andere Moderationshandlungen.
