### ISSUE TITLE
[FEATURE] Implement `report create` slash command

### ISSUE THREAD

**Issue by Kaktushose** [nplay-team/moderation-bot#2]
# Beschreibung
Im neuen Bot werden alle Moderationshandlungen unter einem Command zusammengefasst. Folgende use cases gibt es für den Command:
- Warns
- Timeouts
- Kick
- Tempban
- Permaban

Anhand der angegebenen Command Parameter soll der Bot dynamisch die richtige Aktion ausführen. 

# Vorraussetzungen

Bevor dieses Feature implementiert werden kann, müssen folgende Features bereits implementiert sein

- [x] Bot Login & Command Registration
- [x] Datenbankanbindung
- [x] Permissions-System #3 

# Command Implementation

## Syntax

`/report create <member> <type> <regel> (duration) (delDays)`

## Parameter

1. `member` OptionType: `User`, required: `true`

2. `type` OptionType: `String`, required: `true`, Choices: `warn, timeout, kick, ban`

3. `regel` OptionType: `String`, required: `true`, Choices: Alle 14 Regeln von 1.1 bis 3.7, Beispiel: `§1.1 - Höflichkeit`

4. `duration` OptionType: `String`, required: `false` Für timeouts required, bei bans macht es den ban zu einem tempban, erfordert bot side parsing des im `ISO_DATE_TIME` Format angegebenen Wertes  

5. `delDays`: OptionType: `Integer`, required: `false`, min: `1`, max: `7` gibt optional die deletionDays bei einem Bann an

## Response

- Failed das Parsing der duration oder fehlt die duration beim type timeout muss mit einer Fehlermeldung geantwortet werden und die command execution gilt als beendet. 

- Ansonsten öffnet sich ein Modal mit einem Textfield, type paragraph. Dort muss die Begründung angegeben werden

- Nach erfolgreicher Modal Eingabe wird die Moderationshandlung ausgeführt. Im #modlog Channel wird eine Nachricht geschickt, ebenso erhält der Nutzer eine entsprechende Nachricht

**Comment by SachsenspieltCoding** [comment]
## Progress
  - [x] Warn
  - [ ] Timeout
  - [ ] Kick
  - [ ] Tempban
  - [ ] Ban

**Comment by SachsenspieltCoding** [comment]
Vollständig implementiert mit dae766d91698f4532e854f6fc5b9175cdddc335f 🎉
